let wordString = [[], [], [], [], []];
var i = 0;
let checkedString = false;

document.addEventListener("keydown", (e) => {
  if (e.key === "Backspace") {
    deleteFromString();
  } else if (e.key === "Enter") {
    if (wordString.length === 5) {
      enterAction();
    }
    if (wordString[i]?.length === 5 && i < 5 && checkedString) {
      i += 1;
    }
  } else {
    if (
      wordString[i]?.length !== 5 &&
      e.key.toUpperCase().length === 1 &&
      e.code.substring(0, 3) === "Key"
    ) {
      appendString(e.key.toUpperCase());
    } else if (wordString[i]?.length === 5 && i < 5 && checkedString) {
      i += 1;
      checkedString = false;
    }
  }
  displayString();
});

document.addEventListener("click", (e) => {
  if (e.target.id === "back") {
    deleteFromString();
  } else if (e.target.id === "enter") {
    if (wordString.length === 5) {
      enterAction();
    }
    if (wordString[i]?.length === 5 && i < 5 && checkedString) {
      i += 1;
    }
  } else {
    if (wordString[i]?.length < 5 && e.target.innerHTML.length === 1) {
      appendString(e.target.innerHTML);
    } else if (
      wordString[i]?.length === 5 &&
      e.target.innerHTML.length === 1 &&
      i < 5 &&
      checkedString
    ) {
      i += 1;
      appendString(e.target.innerHTML);
      checkedString = false;
    }
  }
  displayString();
});

const wordList = [
  "THEIR",
  "WOULD",
  "GRIND",
  "STING",
  "ABOUT",
  "SLANG",
  "THERE",
  "PRONE",
  "THINK",
  "TOAST",
  "WHICH",
  "COULD",
  "OTHER",
  "SALTY",
  "SCOOP",
  "THESE",
  "FIRST",
  "THING",
  "DETOX",
  "THOSE",
  "WOMAN",
  "CHILD",
  "AFTER",
  "WORLD",
  "STILL",
  "BLOOM",
  "THREE",
  "STATE",
  "NEVER",
  "LEAVE",
  "WHILE",
  "GREAT",
  "GROUP",
  "BEGIN",
  "WHERE",
  "OLDER",
  "EVERY",
  "WORSE",
  "WORST",
  "START",
  "MIGHT",
  "RULES",
  "BADGE",
  "PLACE",
  "AGAIN",
  "RIGHT",
  "SMALL",
  "NIGHT",
  "POINT",
  "TODAY",
  "BRING",
  "LARGE",
  "UNDER",
  "WATER",
  "WRITE",
  "MONEY",
  "STORY",
  "YOUNG",
  "MONTH",
  "STUDY",
  "ISSUE",
  "BLACK",
  "HOUSE",
  "SINCE",
  "UNTIL",
  "POWER",
  "OFTEN",
  "AMONG",
  "STAND",
  "LATER",
  "WHITE",
  "LEAST",
  "LEARN",
  "WATCH",
  "SPEAK",
  "LEVEL",
  "LOSER",
  "ALLOW",
  "SPEND",
  "PARTY",
  "EARLY",
  "FORCE",
  "OFFER",
  "MAYBE",
  "MUSIC",
  "HUMAN",
  "SERVE",
  "SENSE",
  "BUILD",
  "DEATH",
  "REACH",
  "LOCAL",
  "CLASS",
  "RAISE",
  "FIELD",
  "MAJOR",
  "ALONG",
  "HEART",
  "LIGHT",
  "VOICE",
  "WHOLE",
  "PRICE",
  "CARRY",
  "DRIVE",
  "BREAK",
  "THANK",
  "VALUE",
  "MODEL",
  "AGREE",
  "PAPER",
  "SPACE",
  "TIMES",
  "EVENT",
  "WINDS",
  "WHOSE",
  "PAGES",
  "TABLE",
  "DEALS",
  "COURT",
  "SLIME",
  "TEACH",
  "IMAGE",
  "PHONE",
  "COVER",
  "QUITE",
  "CLEAR",
  "PIECE",
  "MOVIE",
  "NORTH",
  "THIRD",
  "CATCH",
  "CAUSE",
  "PLANT",
  "SHORT",
  "SOUTH",
  "FLOOR",
  "CLOSE",
  "WRONG",
  "SPORT",
  "BOARD",
  "FIGHT",
  "THROW",
  "ORDER",
  "FOCUS",
  "BLOOD",
  "COLOR",
  "STORE",
  "SOUND",
  "ENTER",
  "SHARE",
  "SHOOT",
  "SEVEN",
  "SCENE",
  "STOCK",
  "EIGHT",
  "HAPPY",
  "OCCUR",
  "MEDIA",
  "READY",
  "ARGUE",
  "STAFF",
  "TRADE",
  "GLASS",
  "SKILL",
  "CRIME",
  "STAGE",
  "TRUTH",
  "CHECK",
  "LAUGH",
  "GUESS",
  "PROVE",
  "CLAIM",
  "CURSE",
  "ENJOY",
  "LEGAL",
  "FILES",
  "FINAL",
  "GREEN",
  "ABOVE",
  "TRIAL",
  "RADIO",
  "VISIT",
  "AVOID",
  "PEACE",
  "APPLY",
  "SHAKE",
  "CHAIR",
  "TREAT",
  "STYLE",
  "ADULT",
  "WORRY",
  "RANGE",
  "DREAM",
  "STUFF",
  "HOTEL",
  "HEAVY",
  "TOUGH",
  "EXIST",
  "AGENT",
  "OWNER",
  "AHEAD",
  "COACH",
  "TOTAL",
  "CIVIL",
  "MOUTH",
  "SMILE",
  "SCORE",
  "FRONT",
  "ADMIT",
  "ALONE",
  "FRESH",
  "VIDEO",
  "JUDGE",
  "STARE",
  "TROOP",
  "TRACK",
  "BASIC",
  "PLANE",
  "LABOR",
  "REFER",
  "TOUCH",
  "SLEEP",
  "PRESS",
  "BRAIN",
  "DOZEN",
  "SORRY",
  "STICK",
  "STONE",
  "SCALE",
  "DRINK",
  "TRUCK",
  "SALES",
  "SHAPE",
  "CROWD",
  "HORSE",
  "GUARD",
  "TERMS",
  "QUICK",
  "POUND",
  "BASIS",
  "GUEST",
  "BLOCK",
  "TITLE",
  "FAITH",
  "RIVER",
  "COUNT",
  "MARRY",
  "LIMIT",
  "WORTH",
  "SPEED",
  "CROSS",
  "YOUTH",
  "BROAD",
  "TWICE",
  "GRADE",
  "QUIET",
  "DRESS",
  "AWARE",
  "CHIEF",
  "BELOW",
  "VOTER",
  "MORAL",
  "PHOTO",
  "DAILY",
  "FULLY",
  "ACTOR",
  "BIRTH",
  "CLEAN",
  "TRAIN",
  "PLATE",
  "ALIVE",
  "ABUSE",
  "EXTRA",
  "PAINT",
  "CLIMB",
  "SWEET",
  "METAL",
  "URBAN",
  "LUNCH",
  "SUGAR",
  "ENEMY",
  "PANEL",
  "SIGHT",
  "ADOPT",
  "WORKS",
  "EMPTY",
  "TRAIL",
  "NOVEL",
  "IRAQI",
  "THEME",
  "STORM",
  "UNION",
  "FRUIT",
  "PRIME",
  "DANCE",
  "BEING",
  "SHIFT",
  "TREND",
  "ANGRY",
  "TRULY",
  "EARTH",
  "CHEST",
  "THICK",
  "SHEET",
  "OUGHT",
  "BROWN",
  "SHIRT",
  "PILOT",
  "GUIDE",
  "STEAL",
  "FUNNY",
  "BLAME",
  "CRAZY",
  "CHAIN",
  "SOLVE",
  "EQUAL",
  "FORTH",
  "FRAME",
  "TRUST",
  "OCEAN",
  "TOOTH",
  "SMART",
  "TOPIC",
  "NURSE",
  "ASIDE",
  "DOUBT",
  "GRANT",
  "CLOUD",
  "CHEAP",
  "BEACH",
  "ROUTE",
  "UPPER",
  "TIRED",
  "FEWER",
  "APART",
  "MATCH",
  "PROUD",
  "WASTE",
  "WHEEL",
  "CABLE",
  "RURAL",
  "CREAM",
  "SOLID",
  "NOISE",
  "GRASS",
  "TASTE",
  "SHARP",
  "LOWER",
  "HONOR",
  "KNOCK",
  "ASSET",
  "BREAD",
  "LUCKY",
  "BRIEF",
  "STEEL",
  "SHOUT",
  "LAYER",
  "SLIDE",
  "SHALL",
  "ERROR",
  "PRINT",
  "ALBUM",
  "JOINT",
  "REPLY",
  "CYCLE",
  "GRAND",
  "HELLO",
  "KNIFE",
  "PHASE",
  "QUOTE",
  "ELECT",
  "SAUCE",
  "SHOCK",
  "HABIT",
  "JUICE",
  "ENTRY",
  "MAKER",
  "ASIAN",
  "USUAL",
  "ANGER",
  "ROUND",
  "SMELL",
  "TOWER",
  "SMOKE",
  "COAST",
  "INNER",
  "SWING",
  "MAYOR",
  "FIFTH",
  "FAVOR",
  "WEIGH",
  "FALSE",
  "LATIN",
  "ESSAY",
  "GIANT",
  "DEPTH",
  "SHELL",
  "ONION",
  "BRAND",
  "AWARD",
  "ARISE",
  "ARMED",
  "STAKE",
  "FIBER",
  "MINOR",
  "LABEL",
  "INDEX",
  "DRAFT",
  "ROUGH",
  "DRAMA",
  "CLOCK",
  "SWEEP",
  "SUPER",
  "YIELD",
  "FENCE",
  "BUNCH",
  "FOUND",
  "REACT",
  "CHEEK",
  "APPLE",
  "VIRUS",
  "BLIND",
  "SLAVE",
  "ELITE",
  "TIGHT",
  "BIBLE",
  "CHART",
  "SOLAR",
  "STRIP",
  "SALAD",
  "PAUSE",
  "BENCH",
  "LOVER",
  "NEWLY",
  "IMPLY",
  "PRIDE",
  "IDEAL",
  "CRASH",
  "CRAFT",
  "FAULT",
  "LOOSE",
  "PRIOR",
  "RELAX",
  "STAIR",
  "PROOF",
  "DIRTY",
  "ALTER",
  "SPLIT",
  "VITAL",
  "ADAPT",
  "IRISH",
  "HONEY",
  "TRIBE",
  "SHELF",
  "BUYER",
  "SHADE",
  "MOUNT",
  "ANGLE",
  "CRACK",
  "GIVEN",
  "TRACE",
  "METER",
  "RAPID",
  "FIFTY",
  "PORCH",
  "RIFLE",
  "TRICK",
  "NERVE",
  "RATIO",
  "HUMOR",
  "GLOVE",
  "DELAY",
  "SCOPE",
  "BADLY",
  "EAGER",
  "MOTOR",
  "FLOAT",
  "BLADE",
  "CABIN",
  "YOURS",
  "PITCH",
  "LEMON",
  "NAKED",
  "SHRUG",
  "FLAME",
  "WOUND",
  "FLESH",
  "GRAIN",
  "BRUSH",
  "SEIZE",
  "SHORE",
  "GHOST",
  "AWFUL",
  "PIANO",
  "MOUSE",
  "CHASE",
  "BRICK",
  "PATCH",
  "SWEAR",
  "SLICE",
  "EXACT",
  "UNCLE",
  "GRAVE",
  "COUCH",
  "SHINE",
  "UPSET",
  "ORGAN",
  "MAGIC",
  "JEANS",
  "FLOUR",
  "SLOPE",
  "CANDY",
  "MEDAL",
  "CURVE",
  "LOGIC",
  "HARSH",
  "GREET",
  "MARCH",
  "SNAKE",
  "FLASH",
  "ISLAM",
  "ROMAN",
  "ELBOW",
  "PLEAD",
  "SIXTH",
  "TRUNK",
  "RUMOR",
  "CLOTH",
  "PLAIN",
  "FRAUD",
  "ARRAY",
  "BURST",
  "FLOOD",
  "ARENA",
  "DRIFT",
  "DRAIN",
  "HURRY",
  "WRIST",
  "GUILT",
  "SKIRT",
  "HENCE",
  "AWAIT",
  "SPILL",
  "GRACE",
  "TOWEL",
  "PRIZE",
  "BOOST",
  "ALARM",
  "WEIRD",
  "SWEAT",
  "OUTER",
  "DRUNK",
  "CHAOS",
  "FORTY",
  "LOBBY",
  "TRAIT",
  "THUMB",
  "UNITY",
  "TWIST",
  "SHAME",
  "REBEL",
  "FLUID",
  "CLICK",
  "CARVE",
  "BELLY",
  "ADORE",
  "TRIPS",
  "SCARE",
  "ANKLE",
  "RIDER",
  "CRAWL",
  "BROKE",
  "DONOR",
  "OPERA",
  "CLERK",
  "LASER",
  "REALM",
  "BLEND",
  "PIZZA",
  "CIVIC",
  "STEEP",
  "ALIEN",
  "SCARY",
  "ANGEL",
  "SILLY",
  "RANCH",
  "ELDER",
  "ROAST",
  "ROOTS",
  "DUTCH",
  "GREEK",
  "QUEST",
  "JUROR",
  "STIFF",
  "TOXIC",
  "GRIEF",
  "BUDDY",
  "SWORD",
  "OATER",
  "GLORY",
  "FAINT",
  "QUEEN",
  "INPUT",
  "STEAM",
  "UNITE",
  "EQUIP",
  "BLESS",
  "BONUS",
  "MIXED",
  "ORBIT",
  "GRASP",
  "SPITE",
  "WAGON",
  "SHEER",
  "THIGH",
  "SHEEP",
  "WHALE",
  "SKULL",
  "SPELL",
  "BOOTH",
  "WAIST",
  "ROYAL",
  "PANIC",
  "CRUSH",
  "CLIFF",
  "TUMOR",
  "PULSE",
  "FIXED",
  "DIARY",
  "IRONY",
  "SPOON",
  "MIDST",
  "ALLEY",
  "FLIRT",
  "RIVAL",
  "PUNCH",
  "KNOWN",
  "FIRES",
  "PURSE",
  "CHEAT",
  "FEVER",
  "DRIED",
  "SHOVE",
  "COUGH",
  "STOVE",
  "ALIKE",
  "DOUGH",
  "TRASH",
  "GROSS",
  "SPRAY",
  "BEAST",
  "SHARK",
  "FLEET",
  "DEBUT",
  "SCENT",
  "STACK",
  "CEASE",
  "NASTY",
  "WHEAT",
  "AISLE",
  "EMBED",
  "VOCAL",
  "TREES",
  "RISKY",
  "PASTA",
  "GENRE",
  "MERIT",
  "CHUNK",
  "ROBOT",
  "BOAST",
  "ADDED",
  "SNEAK",
  "BLANK",
  "DYING",
  "SPARE",
  "CLING",
  "BLINK",
  "SQUAD",
  "CHILL",
  "STEER",
  "RALLY",
  "CHEER",
  "STEAK",
  "AWAKE",
  "LIVER",
  "WIDOW",
  "BEARD",
  "BRAKE",
  "VALID",
  "FORUM",
  "ENACT",
  "SUITE",
  "STRAW",
  "GLOBE",
  "BLAST",
  "SCREW",
  "DRILL",
  "CRUEL",
  "GRAPE",
  "CHARM",
  "LOYAL",
  "RADAR",
  "FROWN",
  "SPARK",
  "BLOND",
  "ARROW",
  "RIDGE",
  "BRAVE",
  "DENSE",
  "SUNNY",
  "SWELL",
  "BRIDE",
  "WEAVE",
  "DEVIL",
  "CARGO",
  "SPINE",
  "FATAL",
  "DROWN",
  "KNEEL",
  "NAVAL",
  "SAINT",
  "SHAVE",
  "FRIED",
  "PRANK",
  "PLANK",
];
let randomSelectedWord = wordList[Math.floor(Math.random() * wordList.length)];
const enterAction = () => {
  let checkString = "";
  let index;
  let greenCount = 0;
  checkString = wordString[i].join("").toUpperCase();
  console.log(checkString.length, "length");
  if (checkString.length > 0) {
    if (wordList.includes(checkString)) {
      for (let x = 0; x < checkString.length; x++) {
        for (let y = 0; y < randomSelectedWord.length; y++) {
          if (checkString[x] !== randomSelectedWord[y]) {
            if (
              !document
                .getElementById(`${i}${x}`)
                .classList.contains("green") &&
              !document.getElementById(`${i}${x}`).classList.contains("yellow")
            ) {
              setColor(`${i}${x}`, "gray");
              setColor(`${checkString[x]}`, "gray");
            }
          } else {
            if (x === y) {
              greenCount += 1;
              setColor(`${i}${x}`, "green");
              setColor(`${checkString[x]}`, "green");
            } else {
              if (
                !document.getElementById(`${i}${x}`).classList.contains("green")
              ) {
                setColor(`${i}${x}`, "yellow");
                setColor(`${checkString[x]}`, "yellow");
              }
            }
          }
        }
      }
      checkedString = true;
      if (greenCount === 5) {
        updateToast("", i);
      } else {
        if (i === 4) {
          updateToast(
            `it was ${randomSelectedWord} </br> reload for another word`,
            (i = 6)
          );
        }
      }
    } else {
      updateToast("Not a word in my list!");
      checkedString = false;
    }
  }
};

const appendString = (target) => {
  wordString[i]?.push(target);
};

const deleteFromString = () => {
  wordString[i].pop();
  document.getElementById(`${i}${wordString[i].length}`).innerHTML = "";
};

const displayString = () => {
  for (let k = 0; k < wordString.length; k++) {
    for (let j = 0; j < wordString[k].length; j++) {
      document.getElementById(`${k}${j}`).innerHTML = wordString[k][j];
    }
  }
};

const updateToast = (msg, i = null) => {
  if (i !== null) {
    if (i === 0) {
      msg = "lucky! </br> reload for another word";
    } else if (i === 1) {
      msg = "smart! </br> reload for another word";
    } else if (i === 2) {
      msg = "amazing! </br> reload for another word ";
    } else if (i === 3) {
      msg = "great! </br> reload for another word";
    } else if (i === 4) {
      msg = "finally! </br> reload for another word ";
    }
  } else {
    setTimeout(() => {
      document.getElementById("toast").style.opacity = "0";
    }, 1200);
  }
  document.getElementById("toast").innerHTML = msg;
  document.getElementById("toast").style.opacity = "0.7";
};

const setColor = (id, color) => {
  document.getElementById(id).classList.add(color);
};
const openModal = () => {
  document.getElementById("rules").classList.add("opacity");
};
const closeModal = () => {
  document.getElementById("rules").classList.remove("opacity");
};
